#!/usr/bin/env bash

# nb everything after 9th field are optional tags

DATA=$(cat << EOF
hōra,dēclīnātiō I,fēminīnum,singulāris,hōra,hōram,hōrae,hōrae,hōrā,hour
hōrae,dēclīnātiō I,fēminīnum,plūrālis,hōrae,hōrās,hōrārum,hōrīs,hōrīs,hours
magnus,dēclīnātiō I,masculīnum,singulāris,magnus,magnum,magnī,magnō,magnō,large,dēclīnātiō II
magnus,dēclīnātiō I,masculīnum,plūrālis,magnī,magnōs,magnōrum,magnīs,magnīs,large,dēclīnātiō II
magnus,dēclīnātiō I,fēminīnum,singulāris,magna,magnam,magnae,magnae,magnā,large,dēclīnātiō II
magnus,dēclīnātiō I,fēminīnum,plūrālis,magnae,magnās,magnārum,magnīs,magnīs,large,dēclīnātiō II
magnus,dēclīnātiō I,neutrum,singulāris,magnum,magnum,magnī,magnō,magnō,large,dēclīnātiō II
magnus,dēclīnātiō I,neutrum,plūrālis,magna,magna,magnōrum,magnīs,magnīs,large,dēclīnātiō II
nūllus,dēclīnātiō I,masculīnum,singulāris,nūllus,nūllum,nūllīus,nūllī,nūllō,none,dēclīnātiō II
nūllus,dēclīnātiō I,masculīnum,plūrālis,nūllī,nūllōs,nūllōrum,nūllīs,nūllīs,none,dēclīnātiō II
nūllus,dēclīnātiō I,fēminīnum,singulāris,nūlla,nūllam,nūllīus,nūllī,nūllā,none,dēclīnātiō II
nūllus,dēclīnātiō I,fēminīnum,plūrālis,nūllae,nūllās,nūllārum,nūllīs,nūllīs,none,dēclīnātiō II
nūllus,dēclīnātiō I,neutrum,singulāris,nūllum,nūllum,nūllīus,nūllī,nūllō,none,dēclīnātiō II
nūllus,dēclīnātiō I,neutrum,plūrālis,nūlla,nūlla,nūllōrum,nūllīs,nūllīs,none,dēclīnātiō II
liber,dēclīnātiō II,masculīnum,singulāris,liber,librum,librī,librō,librō,book,dēclīnātiō II
librī,dēclīnātiō II,masculīnum,plūrālis,librī,librōs,librōrum,librīs,librīs,book
servus,dēclīnātiō II,masculīnum,singulāris,servus,servum,servī,servō,servō,servants
servī,dēclīnātiō II,masculīnum,plūrālis,servī,servō,servōrum,servīs,servīs,books
verbum,dēclīnātiō II,neutrum,singulāris,verbum,verbum,verbī,verbō,verbō,word
verba,dēclīnātiō II,neutrum,plūrālis,verba,verba,verbōrum,verbīs,verbīs,words
leō,dēclīnātiō III,masculīnum,singulāris,leō,leōnem,leōnis,leōnī,leōne,lion
leō,dēclīnātiō III,masculīnum,plūrālis,leōnēs,leōnēs,leōnum,leōnibus,leōnibus,lions
mare,dēclīnātiō III,neutrum,singulāris,mare,mare,maris,marī,marī,sea
maria,dēclīnātiō III,neutrum,plūrālis,maria,maria,marium,maribus,maribus,seas
mōns,dēclīnātiō III,masculīnum,singulāris,mōns,montem,montis,montī,monte,mountain
montēs,dēclīnātiō III,masculīnum,plūrālis,montēs,montēs,montium,montibus,montibus,mountains
nāvis,dēclīnātiō III,fēminīnum,singulāris,nāvis,nāvem,nāvis,nāvī,nāve,ship
nāvēs,dēclīnātiō III,fēminīnum,plūrālis,nāvēs,nāvēs,nāvium,nāvibus,nāvibus,ships
nōmen,dēclīnātiō III,neutrum,singulāris,nōmen,nōmen,nōminis,nōminī,nōmine,name
nōmina,dēclīnātiō III,neutrum,plūrālis,nōmina,nōmina,nōminum,nōminibus,nōminibus,names
sōl,dēclīnātiō III,masculīnum,singulāris,sōl,sōlem,sōlis,sōlī,sōle,sun
sōlēs,dēclīnātiō III,masculīnum,plūrālis,sōlēs,sōlēs,sōlum,sōlibus,sōlibus,suns
urbs,dēclīnātiō III,fēminīnum,singulāris,urbs,urbem,urbis,urbī,urbe,city
urbēs,dēclīnātiō III,fēminīnum,plūrālis,urbēs,urbēs,urbium,urbibus,urbibus,cities
vōx,dēclīnātiō III,fēminīnum,singulāris,vōx,vōcem,vōcis,vōcī,vōce,voice
vōcēs,dēclīnātiō III,fēminīnum,plūrālis,vōcēs,vōcēs,vōcum,vōcibus,vōcibus,voices
EOF
)

prompt() {
  read -p '' -n 1 -r <&1
  if [[ $REPLY =~ ^[Qq]$ ]]; then
    exit 0
  fi
}

IFS="|"
args="$*"

if [[ ! -z "$args" ]]; then
  DATA=$(grep -E "$args" <<< "$DATA")

  if [[ -z "$DATA" ]]; then
    echo "no results"
    exit 1
  fi
fi

LOOP=true

while $LOOP; do

  clear

  cont=$(shuf -n 1 <<< "$DATA")

  wd=$(cut -f 1 -d, <(echo -n "$cont"))
  ty=$(cut -f 2 -d, <(echo -n "$cont"))
  ge=$(cut -f 3 -d, <(echo -n "$cont"))
  mu=$(cut -f 4 -d, <(echo -n "$cont"))
  en=$(cut -f 10 -d, <(echo -n "$cont"))

  echo "$wd ($mu, $ge): $en"

  prompt

  echo "$ty"
  echo
  echo "nōm:  $(cut -f 5 -d, <<< "$cont")"
  echo "acc:  $(cut -f 6 -d, <<< "$cont")"
  echo "gen:  $(cut -f 7 -d, <<< "$cont")"
  echo "dat:  $(cut -f 8 -d, <<< "$cont")"
  echo "abl:  $(cut -f 9 -d, <<< "$cont")"

  prompt

done
